version: '2'

services:
  wordpress:
    build: ./
    depends_on:
      - mysql
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DEBUG: 'true'
    volumes:
      - ./wp-content:/var/www/html/wp-content
      - ./plugins:/var/www/html/plugins
      - ./themes:/var/www/html/themes
      - ./vendor:/var/www/html/vendor
      - ./docker/wp-config.d:/var/www/html/wp-config.d
      - ./docker/htaccess_dev:/var/www/html/.htaccess

  mysql:
    image: mariadb
    volumes:
      - ./mariadb_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: therootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
